'use client';

import { useAuthStore } from '@/lib/auth-store';
import { xoomBackendUrl } from '@/lib/axios/getAxios';
import { uploadImageToCloudinary } from '@/lib/helpers/uploadImageToCloudinary';

import { ErrorMessage, Field, Form, Formik } from 'formik';
import { useRouter } from 'next/navigation';
import { useRef, useState } from 'react';
import { toast } from 'react-hot-toast';
import { FiImage, FiVideo, FiX } from 'react-icons/fi';
import { ImSpinner } from 'react-icons/im';
import { IoIosFootball } from 'react-icons/io';
import * as Yup from 'yup';
import ImageDropSingle from '../../../../components/Global/ImageDropSingle';

export default function CreateHighlight({ query }) {
  const { token } = useAuthStore();
  const [thumbnailImage, setThumbnailImage] = useState('');
  const [uploadImageMsg, setUploadImageMsg] = useState('');
  const [fixtureId, setFixtureId] = useState(query?.fixture_id ?? '');
  const [isLoading, setIsLoading] = useState(false);
  const [videoList, setVideoList] = useState(
    query?.video_list ? JSON.parse(query.video_list) : []
  );

  const [isSubmitting, setIsSubmitting] = useState(false);
  const { push } = useRouter();

  // Video upload states
  const [uploadedVideo, setUploadedVideo] = useState(null);
  const [videoPreviewUrl, setVideoPreviewUrl] = useState('');
  const [autoGeneratedThumbnail, setAutoGeneratedThumbnail] = useState('');
  const [isGeneratingThumbnail, setIsGeneratingThumbnail] = useState(false);
  const [isUploadingVideo, setIsUploadingVideo] = useState(false);
  const [thumbnailSource, setThumbnailSource] = useState('auto'); // 'auto' or 'manual'
  const videoRef = useRef(null);
  const canvasRef = useRef(null);
  console.log(query?.video_type, 'query?.video_type');
  // Initial values
  const initialHighlightValue = {
    title: query?.title || '',
    thumbnail_type: query?.video_type || 'none',
    video_type: query?.fixture_id ? 'sportmonk' : 'none',
    youtube_url: '',
    status: '1',
    uploaded_video_url: '',
  };

  // Schema validation
  const getValidationSchema = () => {
    return Yup.object().shape({
      title: Yup.string().required('Title is required.'),
      video_type: Yup.string().oneOf(
        ['none', 'sportmonk', 'youtube', 'upload'],
        'Video Type is required.'
      ),
      youtube_url: Yup.string().when('video_type', {
        is: 'youtube',
        then: () => Yup.string().required('Youtube Url is required.'),
      }),
      thumbnail_type: Yup.string().oneOf(
        ['none', 'image', 'url'],
        'Thumbnail Type is required.'
      ),
      image: Yup.mixed().when(['thumbnail_type', 'video_type'], {
        is: (thumbnail_type, video_type) => {
          // Skip image validation if using auto thumbnail from video upload
          if (
            video_type === 'upload' &&
            thumbnailSource === 'auto' &&
            autoGeneratedThumbnail
          ) {
            return false;
          }
          if (thumbnail_type === 'image' && thumbnailImage != '') {
            return false;
          }

          return false;
        },
        then: () => Yup.mixed().required('Thumbnail Image is required.'),
      }),
      highlight_image: Yup.string().when('thumbnail_type', {
        is: 'url',
        then: () => Yup.string().required('Thumbnail Url is required.'),
      }),
    });
  };
  // Generate thumbnail from video
  const generateThumbnailFromVideo = (videoElement) => {
    return new Promise((resolve) => {
      const canvas = document.createElement('canvas');
      canvas.width = videoElement.videoWidth;
      canvas.height = videoElement.videoHeight;
      const ctx = canvas.getContext('2d');
      ctx.drawImage(videoElement, 0, 0, canvas.width, canvas.height);
      const thumbnailDataUrl = canvas.toDataURL('image/jpeg', 0.8);
      resolve(thumbnailDataUrl);
    });
  };

  // Convert data URL to File
  const dataURLtoFile = (dataurl, filename) => {
    const arr = dataurl.split(',');
    const mime = arr[0].match(/:(.*?);/)[1];
    const bstr = atob(arr[1]);
    let n = bstr.length;
    // eslint-disable-next-line no-undef
    const u8arr = new Uint8Array(n);
    while (n--) {
      u8arr[n] = bstr.charCodeAt(n);
    }
    return new File([u8arr], filename, { type: mime });
  };

  // Handle video upload
  const handleVideoUpload = async (e, setFieldValue) => {
    const file = e.target.files[0];
    if (!file) return;

    // Validate file type
    if (!file.type.startsWith('video/')) {
      toast.error('Please upload a valid video file');
      return;
    }

    // Validate file size (max 100MB)
    if (file.size > 100 * 1024 * 1024) {
      toast.error('Video file size should be less than 100MB');
      return;
    }

    setUploadedVideo(file);
    const previewUrl = URL.createObjectURL(file);
    setVideoPreviewUrl(previewUrl);
    setIsGeneratingThumbnail(true);

    // Create a video element to generate thumbnail
    const video = document.createElement('video');
    video.src = previewUrl;
    video.crossOrigin = 'anonymous';
    video.muted = true;

    video.addEventListener('loadeddata', async () => {
      // Seek to 1 second or 25% of video duration
      video.currentTime = Math.min(1, video.duration * 0.25);
    });

    video.addEventListener('seeked', async () => {
      try {
        const thumbnail = await generateThumbnailFromVideo(video);
        setAutoGeneratedThumbnail(thumbnail);
        setIsGeneratingThumbnail(false);

        // Auto-set thumbnail if using auto mode
        if (thumbnailSource === 'auto') {
          setFieldValue('thumbnail_type', 'image');
        }
      } catch (error) {
        console.error('Error generating thumbnail:', error);
        setIsGeneratingThumbnail(false);
        toast.error('Failed to generate thumbnail');
      }
    });

    video.load();
  };

  // Upload video to Cloudinary
  const uploadVideoToCloudinary = async (videoFile) => {
    const formData = new FormData();
    formData.append('file', videoFile);
    formData.append('upload_preset', 'XoomSports');
    formData.append('resource_type', 'video');

    const response = await fetch(
      `https://api.cloudinary.com/v1_1/${process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME || 'your-cloud-name'}/video/upload`,
      {
        method: 'POST',
        body: formData,
      }
    );

    const data = await response.json();
    return data.secure_url;
  };

  // Remove uploaded video
  const removeUploadedVideo = (setFieldValue) => {
    setUploadedVideo(null);
    setVideoPreviewUrl('');
    setAutoGeneratedThumbnail('');
    setFieldValue('uploaded_video_url', '');
  };

  // Handle Highlight check
  const handleHighlightCheck = async (fixtureId) => {
    setIsLoading(true);
    setFixtureId(fixtureId);
    const { data } = await xoomBackendUrl.post(
      `/api/admin/fixtures/highlights`,
      {
        fixture_id: fixtureId,
      }
    );

    if (data.status) {
      if (data?.data.length === 0) {
        toast.success('No highlights available');
      } else {
        let videos = [];
        data.data.map((video) => videos.push(video.location));
        setVideoList(videos);
      }
      setIsLoading(false);
    } else {
      setIsLoading(false);
      toast.error(data?.message);
    }
    setIsLoading(false);
  };

  // Handle submit form
  const handleSubmit = async (values) => {
    setIsSubmitting(true);
    try {
      let imageUrl = '';
      let videoUrl = '';

      // Upload video if exists
      if (uploadedVideo && values.video_type === 'upload') {
        setIsUploadingVideo(true);
        toast.loading('Uploading video...', { id: 'video-upload' });
        try {
          videoUrl = await uploadVideoToCloudinary(uploadedVideo);
          toast.success('Video uploaded successfully', { id: 'video-upload' });
        } catch (error) {
          toast.error('Failed to upload video', { id: 'video-upload' });
          setIsSubmitting(false);
          setIsUploadingVideo(false);
          return;
        }
        setIsUploadingVideo(false);
      }

      // Upload thumbnail image
      if (thumbnailImage) {
        const uploadPreset = 'XoomSports';
        imageUrl = await uploadImageToCloudinary(thumbnailImage, uploadPreset);
      } else if (autoGeneratedThumbnail && thumbnailSource === 'auto') {
        // Upload auto-generated thumbnail
        const thumbnailFile = dataURLtoFile(
          autoGeneratedThumbnail,
          'thumbnail.jpg'
        );
        const uploadPreset = 'XoomSports';
        imageUrl = await uploadImageToCloudinary(thumbnailFile, uploadPreset);
      }

      const highlightValues = {
        ...values,
        highlight_image: imageUrl ? imageUrl : values.highlight_image,
        videos:
          values.video_type === 'upload' && videoUrl ? [videoUrl] : videoList,
        uploaded_video_url: videoUrl,
      };

      const { data } = await xoomBackendUrl.post(
        '/api/admin/highlights/create',
        highlightValues,
        {
          headers: { Authorization: `Bearer ${token}` },
        }
      );
      if (data.status) {
        push('/xoomadmin/highlights');
        toast.success('Highlight created successfully');
        setIsSubmitting(false);
      }
    } catch (error) {
      toast.error('An unexpected error occurred.');
      setIsSubmitting(false);
    }
  };

  return (
    <div className="mb-5">
      <Formik
        initialValues={initialHighlightValue}
        validationSchema={getValidationSchema()}
        onSubmit={handleSubmit}
        enableReinitialize
      >
        {({ values, handleChange, errors, setFieldValue }) => {
          if (Object.keys(errors).length > 0) {
            console.log('Validation Errors:', errors);
          }
          return (
            <Form className="space-y-4 bg-white mt-3 p-4 rounded-md">
              <div>
                <div className="form-control w-full">
                  <label
                    className="label text-gray-700 font-medium flex items-center justify-start"
                    htmlFor="title"
                  >
                    Title<span className="text-red-500">*</span>
                  </label>
                  <Field
                    id="title"
                    type="text"
                    className="input input-bordered w-full bg-white rounded"
                    name="title"
                  />
                  <ErrorMessage
                    name="title"
                    component="div"
                    className="mt-1 text-red-500"
                  />
                </div>

                <div className="form-control w-full">
                  <label
                    htmlFor="short_description"
                    className="label font-medium flex items-center justify-start text-gray-700 "
                  >
                    Short Description
                  </label>
                  <Field
                    as="textarea"
                    id="short_description"
                    rows={3}
                    className="textarea textarea-bordered bg-white rounded"
                    name="short_description"
                  />
                  <ErrorMessage
                    name="short_description"
                    component="div"
                    className="mt-1 text-red-500"
                  />
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                  <div className="form-control w-full">
                    <label
                      htmlFor="type"
                      className="label font-medium flex items-center justify-start text-gray-700"
                    >
                      Video Type<span className="text-red-500">*</span>
                    </label>
                    <Field
                      as="select"
                      name="video_type"
                      className="input input-bordered w-full bg-white rounded"
                    >
                      <option value="none">None</option>
                      <option value="upload">Upload Video</option>
                      <option value="sportmonk">Sportmonk</option>
                      <option value="youtube">Youtube</option>
                    </Field>
                    <ErrorMessage
                      name="video_type"
                      component="div"
                      className="mt-1 text-red-500"
                    />
                  </div>

                  {values.video_type === 'upload' && (
                    <div className="col-span-2">
                      <label className="label font-medium flex items-center justify-start text-gray-700">
                        Upload Video<span className="text-red-500">*</span>
                      </label>

                      {!uploadedVideo ? (
                        <div className="border-2 border-dashed border-gray-300 rounded-lg p-6 text-center hover:border-green-400 transition-colors">
                          <input
                            type="file"
                            accept="video/*"
                            onChange={(e) =>
                              handleVideoUpload(e, setFieldValue)
                            }
                            className="hidden"
                            id="video-upload"
                          />
                          <label
                            htmlFor="video-upload"
                            className="cursor-pointer flex flex-col items-center"
                          >
                            <FiVideo className="text-4xl text-gray-400 mb-2" />
                            <span className="text-gray-600 font-medium">
                              Click to upload video
                            </span>
                            <span className="text-gray-400 text-sm mt-1">
                              MP4, WebM, MOV (max 100MB)
                            </span>
                          </label>
                        </div>
                      ) : (
                        <div className="border border-gray-200 rounded-lg p-4">
                          <div className="flex items-start justify-between mb-3">
                            <div className="flex items-center gap-3">
                              <FiVideo className="text-2xl text-green-500" />
                              <div>
                                <p className="font-medium text-gray-700 truncate max-w-xs">
                                  {uploadedVideo.name}
                                </p>
                                <p className="text-sm text-gray-400">
                                  {(uploadedVideo.size / (1024 * 1024)).toFixed(
                                    2
                                  )}{' '}
                                  MB
                                </p>
                              </div>
                            </div>
                            <button
                              type="button"
                              onClick={() => removeUploadedVideo(setFieldValue)}
                              className="text-red-500 hover:text-red-700 p-1"
                            >
                              <FiX className="text-xl" />
                            </button>
                          </div>

                          {videoPreviewUrl && (
                            <video
                              ref={videoRef}
                              src={videoPreviewUrl}
                              controls
                              className="w-full max-h-48 rounded-lg bg-black"
                            />
                          )}
                        </div>
                      )}

                      {/* Thumbnail Options for Video Upload */}
                      {uploadedVideo && (
                        <div className="mt-4 p-4 bg-gray-50 rounded-lg">
                          <label className="label font-medium flex items-center justify-start text-gray-700 mb-2">
                            <FiImage className="mr-2" />
                            Thumbnail Options
                          </label>

                          <div className="flex gap-4 mb-3">
                            <label className="flex items-center gap-2 cursor-pointer">
                              <input
                                type="radio"
                                name="thumbnailSource"
                                value="auto"
                                checked={thumbnailSource === 'auto'}
                                onChange={() => setThumbnailSource('auto')}
                                className="radio radio-success radio-sm"
                              />
                              <span className="text-sm text-gray-600">
                                Auto-generate from video
                              </span>
                            </label>
                            <label className="flex items-center gap-2 cursor-pointer">
                              <input
                                type="radio"
                                name="thumbnailSource"
                                value="manual"
                                checked={thumbnailSource === 'manual'}
                                onChange={() => {
                                  setThumbnailSource('manual');
                                  setFieldValue('thumbnail_type', 'image');
                                }}
                                className="radio radio-success radio-sm"
                              />
                              <span className="text-sm text-gray-600">
                                Upload custom thumbnail
                              </span>
                            </label>
                          </div>

                          {/* Auto-generated Thumbnail Preview */}
                          {thumbnailSource === 'auto' && (
                            <div>
                              {isGeneratingThumbnail ? (
                                <div className="flex items-center gap-2 text-gray-500">
                                  <ImSpinner className="animate-spin" />
                                  <span className="text-sm">
                                    Generating thumbnail...
                                  </span>
                                </div>
                              ) : autoGeneratedThumbnail ? (
                                <div>
                                  <p className="text-sm text-gray-500 mb-2">
                                    Auto-generated thumbnail:
                                  </p>
                                  <img
                                    src={autoGeneratedThumbnail}
                                    alt="Auto-generated thumbnail"
                                    className="w-48 h-auto rounded-lg border border-gray-200"
                                  />
                                </div>
                              ) : null}
                            </div>
                          )}

                          {/* Manual Thumbnail Upload */}
                          {thumbnailSource === 'manual' && (
                            <div className="mt-2">
                              <input
                                type="file"
                                accept="image/*"
                                onChange={(e) => {
                                  const file = e.target.files[0];
                                  if (file) {
                                    setThumbnailImage(file);
                                    setUploadImageMsg('');
                                    setFieldValue('thumbnail_type', 'image');
                                  }
                                }}
                                className="file-input file-input-bordered file-input-sm w-full bg-white"
                              />
                              {thumbnailImage && (
                                <div className="mt-2">
                                  <img
                                    src={URL.createObjectURL(thumbnailImage)}
                                    alt="Custom thumbnail preview"
                                    className="w-48 h-auto rounded-lg border border-gray-200"
                                  />
                                </div>
                              )}
                            </div>
                          )}
                        </div>
                      )}
                    </div>
                  )}

                  {values.video_type == 'sportmonk' && (
                    <div>
                      <label
                        className="label font-medium flex items-center justify-start text-gray-700"
                        htmlFor="fixture_id"
                      >
                        Fixture ID<span className="text-red-500">*</span>
                      </label>
                      <Field
                        id="fixture_id"
                        type="text"
                        className="input input-bordered w-full bg-white rounded"
                        name="fixture_id"
                        onChange={(e) => {
                          handleChange(e);
                          const fixtureId = e.target.value;
                          handleHighlightCheck(fixtureId, setFieldValue);
                        }}
                      />
                    </div>
                  )}

                  {values.video_type == 'youtube' && (
                    <div>
                      <label
                        className="label font-medium flex items-center justify-start text-gray-700"
                        htmlFor="youtube_url"
                      >
                        Youtube Url<span className="text-red-500">*</span>
                      </label>
                      <Field
                        id="youtube_url"
                        type="text"
                        className="input input-bordered w-full bg-white rounded"
                        name="youtube_url"
                        onChange={(e) => {
                          handleChange(e);
                          const url = e.target.value;
                          const videoId = url.split('v=')[1];
                          setFieldValue('thumbnail_type', 'url');
                          setFieldValue(
                            'highlight_image',
                            `https://img.youtube.com/vi/${videoId}/0.jpg`
                          );
                        }}
                      />
                      <ErrorMessage
                        name="youtube_url"
                        component="div"
                        className="mt-1 text-red-500"
                      />
                    </div>
                  )}

                  {values.video_type == 'sportmonk' && (
                    <div className="mb-5">
                      <label className="label font-medium flex items-center justify-start text-gray-700">
                        Video List
                      </label>
                      {!isLoading ? (
                        <div className="flex flex-col dark:border-[#1b2e4b]">
                          {fixtureId ? (
                            videoList?.length > 0 ? (
                              videoList.map((highlight, index) => (
                                <p
                                  key={index}
                                  className="mb-2 rounded-md border border-white-light bg-[#eee] px-4 py-2.5 dark:border-[#1b2e4b] dark:hover:bg-[#eee]/10"
                                >
                                  {highlight}
                                </p>
                              ))
                            ) : (
                              <p className="mb-2 rounded-md border border-white-light bg-[#eee] px-4 py-2.5 dark:border-[#1b2e4b] dark:hover:bg-[#eee]/10">
                                No Highlights Available!
                              </p>
                            )
                          ) : (
                            <p className="mb-2 rounded-md border border-white-light bg-[#eee] px-4 py-2.5 dark:border-[#1b2e4b] dark:hover:bg-[#eee]/10">
                              Enter Fixture ID!
                            </p>
                          )}
                        </div>
                      ) : (
                        <div className="animate-bounce">
                          <IoIosFootball className="animate-spin text-3xl text-green-400" />
                        </div>
                      )}
                    </div>
                  )}
                </div>
                {values.video_type == 'sportmonk' ||
                  (values.video_type == 'youtube' && (
                    <div className="w-100">
                      <div>
                        <label
                          className="label font-medium flex items-center justify-start text-gray-700"
                          htmlFor="type"
                        >
                          Thumbnail Image Type
                        </label>
                        <div>
                          <Field
                            as="select"
                            className="input input-bordered w-full bg-white rounded"
                            name="thumbnail_type"
                          >
                            <option value="none">None</option>
                            <option value="url">Url</option>
                            <option value="image">Image</option>
                          </Field>
                          <ErrorMessage
                            name="thumbnail_type"
                            component="div"
                            className="mt-1 text-red-500"
                          />
                        </div>
                      </div>
                    </div>
                  ))}
                <div className="col-span-12">
                  <label className="form-control w-full">
                    {values?.thumbnail_type === 'url' && (
                      <>
                        <div className="label">
                          <span className="label-text font-medium">
                            Image Url <span className="text-red-500">*</span>{' '}
                            <ErrorMessage
                              name="highlight_image"
                              component={({ children }) => (
                                <span className="text-sm text-red-600">
                                  ({children})
                                </span>
                              )}
                            />
                          </span>
                        </div>
                        <Field
                          className="input input-bordered w-full bg-white"
                          name="highlight_image"
                        />
                        {values?.highlight_image &&
                          /^(ftp|https):\/\/[^ "]+$/.test(
                            values?.highlight_image
                          ) && (
                            <img
                              src={values.highlight_image}
                              alt="Image"
                              className="aspect-video w-52 object-cover rounded-md mt-3"
                            />
                          )}
                      </>
                    )}
                  </label>
                  {values.thumbnail_type === 'image' &&
                    values.video_type != 'upload' && (
                      <div>
                        <div className="label">
                          <span className="label-text font-medium">
                            Upload Image <span className="text-red-500">*</span>{' '}
                            {uploadImageMsg && (
                              <span className="text-sm text-red-600">
                                ({uploadImageMsg})
                              </span>
                            )}
                          </span>
                        </div>
                        <ImageDropSingle
                          className="mt-3"
                          value={thumbnailImage}
                          onChange={(image) => {
                            setUploadImageMsg('');
                            setThumbnailImage(image);
                          }}
                        />
                      </div>
                    )}
                </div>

                <div>
                  <label
                    className="label font-medium flex items-center justify-start text-gray-700"
                    htmlFor="type"
                  >
                    Status
                  </label>
                  <div>
                    <Field
                      as="select"
                      name="status"
                      className="input input-bordered w-full bg-white rounded"
                    >
                      <option value="1">Active</option>
                      <option value="0">Inactive</option>
                    </Field>
                  </div>
                </div>
                <div className="flex items-center justify-end">
                  <button
                    type="submit"
                    className="btn btn-success rounded-md btn-sm mt-3 text-gray-700"
                    disabled={isSubmitting || isUploadingVideo}
                  >
                    {isUploadingVideo
                      ? 'Uploading Video...'
                      : 'Create Highlight'}{' '}
                    {(isSubmitting || isUploadingVideo) && (
                      <ImSpinner className="ml-2 animate-spin" />
                    )}
                  </button>
                </div>
              </div>
            </Form>
          );
        }}
      </Formik>
    </div>
  );
}
