'use client';

import GlobalLoading from '@/components/Global/GlobalLoading';
import { useAuthStore } from '@/lib/auth-store';
import { xoomBackendUrl } from '@/lib/axios/getAxios';
import { uploadImageToCloudinary } from '@/lib/helpers/uploadImageToCloudinary';
import { ErrorMessage, Field, Form, Formik } from 'formik';
import { useRouter } from 'next/navigation';
import { useRef, useState } from 'react';
import { toast } from 'react-hot-toast';
import { FiImage, FiVideo, FiX } from 'react-icons/fi';
import { ImSpinner } from 'react-icons/im';
import { useQuery } from 'react-query';
import * as Yup from 'yup';
import ImageDropSingle from '../../../../components/Global/ImageDropSingle';

export default function UpdateHighlight({ highlightId }) {
  const [isUpdating, setIsUpdating] = useState(false);
  const [initialValues, setInitialValues] = useState({
    title: '',
    short_description: '',
    status: '1',
    thumbnail_type: 'none',
    video_type: 'none',
    youtube_url: '',
    fixture_id: '',
    videos: [],
    highlight_image: '',
  });

  const [videoList, setVideoList] = useState([]);
  const [thumbnailImage, setThumbnailImage] = useState('');
  const [autoGeneratedThumbnail, setAutoGeneratedThumbnail] = useState('');
  const [isGeneratingThumbnail, setIsGeneratingThumbnail] = useState(false);
  const [videoPreviewUrl, setVideoPreviewUrl] = useState('');
  const [thumbnailSource, setThumbnailSource] = useState('auto'); // 'auto' or 'manual'
  const videoRef = useRef(null);
  // NEW STATES
  const [uploadedVideo, setUploadedVideo] = useState(null);
  const [videoPreview, setVideoPreview] = useState('');
  const [isUploadingVideo, setIsUploadingVideo] = useState(false);
  const [uploadImageMsg, setUploadImageMsg] = useState('');

  const { token } = useAuthStore();
  const { push } = useRouter();

  // Remove uploaded video
  const removeUploadedVideo = (setFieldValue) => {
    setUploadedVideo(null);
    setVideoPreviewUrl('');
    setAutoGeneratedThumbnail('');
    setFieldValue('uploaded_video_url', '');
  };

  const { isLoading } = useQuery(
    ['admin-single-highlight', highlightId],
    async () => {
      const { data } = await xoomBackendUrl.get(
        `/api/admin/highlights/${highlightId}`,
        {
          headers: { Authorization: `Bearer ${token}` },
        }
      );

      if (data?.data) {
        const d = data.data;

        setInitialValues({
          title: d.title || '',
          short_description: d.short_description || '',
          status: d.status || '1',
          thumbnail_type: 'url' || 'none',
          video_type: d.video_type || 'none',
          youtube_url: d.youtube_url || '',
          fixture_id: d.fixture_id || '',
          videos: d.videos || [],
          highlight_image: d.highlight_image || '',
        });

        setVideoList(d.videos || []);
      }
    },
    {
      enabled: !!highlightId && !!token,
      cacheTime: 0,
    }
  );

  if (isLoading) return <GlobalLoading />;

  // validation
  const validationSchema = Yup.object().shape({
    title: Yup.string().required('Title is required.'),
    video_type: Yup.string().oneOf(
      ['none', 'sportmonk', 'youtube', 'upload'],
      'Video Type is required.'
    ),
    youtube_url: Yup.string().when('video_type', {
      is: 'youtube',
      then: () => Yup.string().required('Youtube Url is required.'),
    }),
    thumbnail_type: Yup.string().oneOf(
      ['none', 'image', 'url'],
      'Thumbnail Type is required.'
    ),
    highlight_image: Yup.string().when('thumbnail_type', {
      is: 'url',
      then: () => Yup.string().required('Image Url is required.'),
    }),
  });

  // upload video
  const uploadVideoToCloudinary = async (file) => {
    const cloudName = process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME;
    const formData = new FormData();
    formData.append('file', file);
    formData.append('upload_preset', 'XoomSports');

    const res = await fetch(
      `https://api.cloudinary.com/v1_1/${cloudName}/video/upload`,
      { method: 'POST', body: formData }
    );

    const data = await res.json();
    return data.secure_url;
  };

  // Convert data URL to File
  const dataURLtoFile = (dataurl, filename) => {
    const arr = dataurl.split(',');
    const mime = arr[0].match(/:(.*?);/)[1];
    const bstr = atob(arr[1]);
    let n = bstr.length;
    // eslint-disable-next-line no-undef
    const u8arr = new Uint8Array(n);
    while (n--) {
      u8arr[n] = bstr.charCodeAt(n);
    }
    return new File([u8arr], filename, { type: mime });
  };
  const handleSubmit = async (values) => {
    setIsUpdating(true);

    try {
      let imageUrl = '';
      let videoUrl = '';

      // upload video if new
      // Upload video if exists
      if (uploadedVideo && values.video_type === 'upload') {
        setIsUploadingVideo(true);
        toast.loading('Uploading video...', { id: 'video-upload' });
        try {
          videoUrl = await uploadVideoToCloudinary(uploadedVideo);
          toast.success('Video uploaded successfully', { id: 'video-upload' });
        } catch (error) {
          toast.error('Failed to upload video', { id: 'video-upload' });
          setIsUpdating(false);
          setIsUploadingVideo(false);
          return;
        }
        setIsUploadingVideo(false);
      }

      // Upload thumbnail image
      if (thumbnailImage) {
        const uploadPreset = 'XoomSports';
        imageUrl = await uploadImageToCloudinary(thumbnailImage, uploadPreset);
      } else if (autoGeneratedThumbnail && thumbnailSource === 'auto') {
        // Upload auto-generated thumbnail
        const thumbnailFile = dataURLtoFile(
          autoGeneratedThumbnail,
          'thumbnail.jpg'
        );
        const uploadPreset = 'XoomSports';
        imageUrl = await uploadImageToCloudinary(thumbnailFile, uploadPreset);
      }

      const highlightValues = {
        ...values,
        highlight_image: imageUrl ? imageUrl : values.highlight_image,
        videos:
          values.video_type === 'upload' && videoUrl ? [videoUrl] : videoList,
        uploaded_video_url: videoUrl,
      };

      const { data } = await xoomBackendUrl.put(
        `/api/admin/highlights/${highlightId}`,
        highlightValues,
        {
          headers: { Authorization: `Bearer ${token}` },
        }
      );

      if (data.status) {
        push('/xoomadmin/highlights');
        toast.success('Highlight updated successfully');
      }
    } catch (error) {
      toast.error('Update failed');
    } finally {
      setIsUpdating(false);
    }
  };

  const handleVideoUpload = async (e, setFieldValue) => {
    const file = e.target.files[0];
    if (!file) return;

    // Validate file type
    if (!file.type.startsWith('video/')) {
      toast.error('Please upload a valid video file');
      return;
    }

    // Validate file size (max 100MB)
    if (file.size > 100 * 1024 * 1024) {
      toast.error('Video file size should be less than 100MB');
      return;
    }

    setUploadedVideo(file);
    const previewUrl = URL.createObjectURL(file);
    setVideoPreviewUrl(previewUrl);
    setIsGeneratingThumbnail(true);

    // Create a video element to generate thumbnail
    const video = document.createElement('video');
    video.src = previewUrl;
    video.crossOrigin = 'anonymous';
    video.muted = true;

    video.addEventListener('loadeddata', async () => {
      // Seek to 1 second or 25% of video duration
      video.currentTime = Math.min(1, video.duration * 0.25);
    });

    // Generate thumbnail from video
    const generateThumbnailFromVideo = (videoElement) => {
      return new Promise((resolve) => {
        const canvas = document.createElement('canvas');
        canvas.width = videoElement.videoWidth;
        canvas.height = videoElement.videoHeight;
        const ctx = canvas.getContext('2d');
        ctx.drawImage(videoElement, 0, 0, canvas.width, canvas.height);
        const thumbnailDataUrl = canvas.toDataURL('image/jpeg', 0.8);
        resolve(thumbnailDataUrl);
      });
    };
    video.addEventListener('seeked', async () => {
      try {
        const thumbnail = await generateThumbnailFromVideo(video);
        setAutoGeneratedThumbnail(thumbnail);
        setIsGeneratingThumbnail(false);

        // Auto-set thumbnail if using auto mode
        if (thumbnailSource === 'auto') {
          setFieldValue('thumbnail_type', 'image');
        }
      } catch (error) {
        console.error('Error generating thumbnail:', error);
        setIsGeneratingThumbnail(false);
        toast.error('Failed to generate thumbnail');
      }
    });

    video.load();
  };

  return (
    <div className="mb-5">
      <Formik
        initialValues={initialValues}
        validationSchema={validationSchema}
        onSubmit={handleSubmit}
        enableReinitialize
      >
        {({ values, setFieldValue }) => (
          <Form className="space-y-4 bg-white mt-3 p-4 rounded-md">
            <Field name="title" className="input input-bordered w-full" />
            <ErrorMessage
              name="title"
              component="div"
              className="text-red-500"
            />

            <Field
              as="textarea"
              name="short_description"
              className="textarea w-full"
            />

            {/* VIDEO TYPE */}
            <Field
              as="select"
              name="video_type"
              className="input input-bordered w-full"
            >
              <option value="none">None</option>
              <option value="upload">Upload Video</option>
              <option value="sportmonk">Sportmonk</option>
              <option value="youtube">Youtube</option>
            </Field>

            {/* YOUTUBE */}
            {values.video_type === 'youtube' && (
              <Field name="youtube_url" className="input w-full" />
            )}

            {/* SPORTMONK */}
            {values.video_type === 'sportmonk' && videoList.length > 0 && (
              <div>
                {videoList.map((v, i) => (
                  <p key={i}>{v}</p>
                ))}
              </div>
            )}

            {values.video_type === 'upload' && (
              <div className="col-span-2">
                <label className="label font-medium flex items-center justify-start text-gray-700">
                  Upload Video<span className="text-red-500">*</span>
                </label>

                {!uploadedVideo ? (
                  <div className="border-2 border-dashed border-gray-300 rounded-lg p-6 text-center hover:border-green-400 transition-colors">
                    <input
                      type="file"
                      accept="video/*"
                      onChange={(e) => handleVideoUpload(e, setFieldValue)}
                      className="hidden"
                      id="video-upload"
                    />
                    <label
                      htmlFor="video-upload"
                      className="cursor-pointer flex flex-col items-center"
                    >
                      <FiVideo className="text-4xl text-gray-400 mb-2" />
                      <span className="text-gray-600 font-medium">
                        Click to upload video
                      </span>
                      <span className="text-gray-400 text-sm mt-1">
                        MP4, WebM, MOV (max 100MB)
                      </span>
                    </label>
                  </div>
                ) : (
                  <div className="border border-gray-200 rounded-lg p-4">
                    <div className="flex items-start justify-between mb-3">
                      <div className="flex items-center gap-3">
                        <FiVideo className="text-2xl text-green-500" />
                        <div>
                          <p className="font-medium text-gray-700 truncate max-w-xs">
                            {uploadedVideo.name}
                          </p>
                          <p className="text-sm text-gray-400">
                            {(uploadedVideo.size / (1024 * 1024)).toFixed(2)} MB
                          </p>
                        </div>
                      </div>
                      <button
                        type="button"
                        onClick={() => removeUploadedVideo(setFieldValue)}
                        className="text-red-500 hover:text-red-700 p-1"
                      >
                        <FiX className="text-xl" />
                      </button>
                    </div>

                    {videoPreviewUrl && (
                      <video
                        ref={videoRef}
                        src={videoPreviewUrl}
                        controls
                        className="w-full max-h-48 rounded-lg bg-black"
                      />
                    )}
                  </div>
                )}

                {/* Thumbnail Options for Video Upload */}
                {uploadedVideo && (
                  <div className="mt-4 p-4 bg-gray-50 rounded-lg">
                    <label className="label font-medium flex items-center justify-start text-gray-700 mb-2">
                      <FiImage className="mr-2" />
                      Thumbnail Options
                    </label>

                    <div className="flex gap-4 mb-3">
                      <label className="flex items-center gap-2 cursor-pointer">
                        <input
                          type="radio"
                          name="thumbnailSource"
                          value="auto"
                          checked={thumbnailSource === 'auto'}
                          onChange={() => setThumbnailSource('auto')}
                          className="radio radio-success radio-sm"
                        />
                        <span className="text-sm text-gray-600">
                          Auto-generate from video
                        </span>
                      </label>
                      <label className="flex items-center gap-2 cursor-pointer">
                        <input
                          type="radio"
                          name="thumbnailSource"
                          value="manual"
                          checked={thumbnailSource === 'manual'}
                          onChange={() => {
                            setThumbnailSource('manual');
                            setFieldValue('thumbnail_type', 'image');
                          }}
                          className="radio radio-success radio-sm"
                        />
                        <span className="text-sm text-gray-600">
                          Upload custom thumbnail
                        </span>
                      </label>
                    </div>

                    {/* Auto-generated Thumbnail Preview */}
                    {thumbnailSource === 'auto' && (
                      <div>
                        {isGeneratingThumbnail ? (
                          <div className="flex items-center gap-2 text-gray-500">
                            <ImSpinner className="animate-spin" />
                            <span className="text-sm">
                              Generating thumbnail...
                            </span>
                          </div>
                        ) : autoGeneratedThumbnail ? (
                          <div>
                            <p className="text-sm text-gray-500 mb-2">
                              Auto-generated thumbnail:
                            </p>
                            <img
                              src={autoGeneratedThumbnail}
                              alt="Auto-generated thumbnail"
                              className="w-48 h-auto rounded-lg border border-gray-200"
                            />
                          </div>
                        ) : null}
                      </div>
                    )}

                    {/* Manual Thumbnail Upload */}
                    {thumbnailSource === 'manual' && (
                      <div className="mt-2">
                        <input
                          type="file"
                          accept="image/*"
                          onChange={(e) => {
                            const file = e.target.files[0];
                            if (file) {
                              setThumbnailImage(file);
                              setUploadImageMsg('');
                              setFieldValue('thumbnail_type', 'image');
                            }
                          }}
                          className="file-input file-input-bordered file-input-sm w-full bg-white"
                        />
                        {thumbnailImage && (
                          <div className="mt-2">
                            <img
                              src={URL.createObjectURL(thumbnailImage)}
                              alt="Custom thumbnail preview"
                              className="w-48 h-auto rounded-lg border border-gray-200"
                            />
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                )}
              </div>
            )}

            {/* THUMBNAIL */}
            {values.video_type != 'upload' && (
              <Field as="select" name="thumbnail_type" className="input w-full">
                <option value="none">None</option>
                <option value="url">URL</option>
                <option value="image">Image</option>
              </Field>
            )}

            {values.thumbnail_type === 'url' && (
              <>
                <Field
                  name="highlight_image"
                  className="input input-bordered w-full"
                />{' '}
                {values.highlight_image && (
                  <img
                    src={values.highlight_image}
                    className="w-40 mt-2 rounded"
                  />
                )}{' '}
              </>
            )}

            {values.thumbnail_type === 'image' &&
              values.video_type != 'upload' && (
                <ImageDropSingle
                  value={thumbnailImage}
                  onChange={setThumbnailImage}
                />
              )}

            {/* STATUS */}
            <Field as="select" name="status" className="input w-full">
              <option value="1">Active</option>
              <option value="0">Inactive</option>
            </Field>

            <button
              type="submit"
              className="btn btn-success"
              disabled={isUpdating || isUploadingVideo}
            >
              {isUploadingVideo ? 'Uploading Video...' : 'Update Highlight'}
              {(isUpdating || isUploadingVideo) && (
                <ImSpinner className="ml-2 animate-spin" />
              )}
            </button>
          </Form>
        )}
      </Formik>
    </div>
  );
}
